# Generated by Django 2.2.1 on 2019-09-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to='meetup.UserInstance'),
        ),
    ]
